services:
  edna:
    build:
      context: .
      dockerfile: Dockerfile
    image: edna:latest
    container_name: edna
    expose:
      - "9325"
    restart: unless-stopped
    command: "-run-prod"
